import type { Metadata } from "next"
import { Anuphan } from "next/font/google"
import "./globals.css"
import AutoWorker from '@/components/auto-worker'
import '@/lib/env'

/*
 * One family for Thai and Latin. The app's copy mixes both in the same
 * sentence constantly — album titles, buttons, counts — and a Latin-only
 * face left every Thai run to whatever the device happened to substitute,
 * so the two scripts never shared a weight or a rhythm.
 */
const anuphan = Anuphan({
  variable: "--font-anuphan",
  subsets: ["latin", "thai"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
})

export const metadata: Metadata = {
  title: "Ciiya app",
  description: "Generated by Ciiya",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="th"
      className={`${anuphan.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}

        {/* Background worker */}
        <AutoWorker />
      </body>
    </html>
  )
}
