-- Shared, owner-scoped foundation for Ciiya AI features.
-- The first consumer is album insights; portfolio, notification and operations
-- assistants can reuse the same job/suggestion/audit lifecycle.

create table if not exists public.ai_jobs (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users(id) on delete cascade,
  album_id uuid references public.albums(id) on delete cascade,
  feature text not null,
  status text not null default 'pending',
  progress smallint not null default 0,
  input jsonb not null default '{}'::jsonb,
  output jsonb,
  error_message text,
  attempts smallint not null default 0,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_jobs_feature_check check (
    feature in (
      'gallery_assistant',
      'portfolio_designer',
      'client_selection',
      'analytics_summary',
      'notification_writer',
      'operations_assistant'
    )
  ),
  constraint ai_jobs_status_check check (
    status in ('pending', 'processing', 'completed', 'failed', 'cancelled')
  ),
  constraint ai_jobs_progress_check check (progress between 0 and 100),
  constraint ai_jobs_attempts_check check (attempts between 0 and 20)
);

create index if not exists idx_ai_jobs_owner_created
on public.ai_jobs(owner_id, created_at desc);

create index if not exists idx_ai_jobs_album_feature_created
on public.ai_jobs(album_id, feature, created_at desc)
where album_id is not null;

create index if not exists idx_ai_jobs_pending
on public.ai_jobs(status, created_at)
where status in ('pending', 'processing');

drop trigger if exists trg_ai_jobs_updated_at on public.ai_jobs;
create trigger trg_ai_jobs_updated_at
before update on public.ai_jobs
for each row execute procedure public.set_updated_at();

create table if not exists public.ai_suggestions (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.ai_jobs(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  album_id uuid references public.albums(id) on delete cascade,
  feature text not null,
  suggestion_type text not null,
  title text not null,
  summary text not null,
  payload jsonb not null default '{}'::jsonb,
  confidence numeric(4, 3),
  status text not null default 'pending',
  applied_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ai_suggestions_status_check check (
    status in ('pending', 'applied', 'dismissed')
  ),
  constraint ai_suggestions_confidence_check check (
    confidence is null or (confidence >= 0 and confidence <= 1)
  )
);

create index if not exists idx_ai_suggestions_owner_status
on public.ai_suggestions(owner_id, status, created_at desc);

create index if not exists idx_ai_suggestions_album_feature
on public.ai_suggestions(album_id, feature, created_at desc)
where album_id is not null;

drop trigger if exists trg_ai_suggestions_updated_at on public.ai_suggestions;
create trigger trg_ai_suggestions_updated_at
before update on public.ai_suggestions
for each row execute procedure public.set_updated_at();

create table if not exists public.ai_audit_logs (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  job_id uuid references public.ai_jobs(id) on delete set null,
  feature text not null,
  action text not null,
  actor_type text not null default 'system',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint ai_audit_logs_actor_check check (
    actor_type in ('user', 'system', 'worker', 'admin')
  )
);

create index if not exists idx_ai_audit_logs_owner_created
on public.ai_audit_logs(owner_id, created_at desc);

alter table public.ai_jobs enable row level security;
alter table public.ai_suggestions enable row level security;
alter table public.ai_audit_logs enable row level security;

drop policy if exists "ai_jobs_owner_select" on public.ai_jobs;
create policy "ai_jobs_owner_select"
on public.ai_jobs for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists "ai_suggestions_owner_select" on public.ai_suggestions;
create policy "ai_suggestions_owner_select"
on public.ai_suggestions for select
to authenticated
using (owner_id = auth.uid());

drop policy if exists "ai_suggestions_owner_update" on public.ai_suggestions;
create policy "ai_suggestions_owner_update"
on public.ai_suggestions for update
to authenticated
using (owner_id = auth.uid())
with check (owner_id = auth.uid());

drop policy if exists "ai_audit_logs_owner_select" on public.ai_audit_logs;
create policy "ai_audit_logs_owner_select"
on public.ai_audit_logs for select
to authenticated
using (owner_id = auth.uid());

revoke all on public.ai_jobs from anon, authenticated;
revoke all on public.ai_suggestions from anon, authenticated;
revoke all on public.ai_audit_logs from anon, authenticated;

grant select on public.ai_jobs to authenticated;
grant select, update(status, applied_at, updated_at) on public.ai_suggestions to authenticated;
grant select on public.ai_audit_logs to authenticated;

grant all on public.ai_jobs to service_role;
grant all on public.ai_suggestions to service_role;
grant all on public.ai_audit_logs to service_role;
grant usage, select on sequence public.ai_audit_logs_id_seq to service_role;

