import crypto from 'node:crypto'
import { cp, mkdir, open, readFile, rename, stat, writeFile } from 'node:fs/promises'
import os from 'node:os'
import path from 'node:path'

export type CiiyaSyncLightroomPluginStatus = {
  supported: boolean
  installed: boolean
  pluginPath: string | null
  version: string | null
}

function pluginRoot(platform = process.platform) {
  if (platform === 'darwin') {
    return path.join(
      os.homedir(),
      'Library',
      'Application Support',
      'Adobe',
      'Lightroom',
      'Modules'
    )
  }
  if (platform === 'win32') {
    const appData = process.env.APPDATA
    return appData
      ? path.join(appData, 'Adobe', 'Lightroom', 'Modules')
      : path.join(os.homedir(), 'AppData', 'Roaming', 'Adobe', 'Lightroom', 'Modules')
  }
  return null
}

async function atomicWrite(filePath: string, contents: string) {
  await mkdir(path.dirname(filePath), { recursive: true })
  const temporary = `${filePath}.tmp-${process.pid}-${crypto.randomUUID()}`
  await writeFile(temporary, contents, { encoding: 'utf8', mode: 0o600 })
  const handle = await open(temporary, 'r+')
  try {
    await handle.sync()
  } finally {
    await handle.close()
  }
  await rename(temporary, filePath)
}

function luaString(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

export class CiiyaSyncBridgeSecretStore {
  private cached: string | null = null

  constructor(readonly filePath: string) {}

  async loadOrCreate() {
    if (this.cached) return this.cached
    try {
      const value = (await readFile(this.filePath, 'utf8')).trim()
      if (/^[A-Za-z0-9_-]{43}$/.test(value)) {
        this.cached = value
        return value
      }
    } catch {
      // A missing or invalid local-only secret is rotated below.
    }
    const value = crypto.randomBytes(32).toString('base64url')
    await atomicWrite(this.filePath, `${value}\n`)
    this.cached = value
    return value
  }
}

export class CiiyaSyncLightroomPluginInstaller {
  constructor(
    readonly sourcePath: string,
    private platform = process.platform,
    private destinationRootOverride?: string
  ) {}

  destinationPath() {
    const root = this.destinationRootOverride || pluginRoot(this.platform)
    return root ? path.join(root, 'CiiyaSync.lrplugin') : null
  }

  async status(): Promise<CiiyaSyncLightroomPluginStatus> {
    const destination = this.destinationPath()
    if (!destination) {
      return {
        supported: false,
        installed: false,
        pluginPath: null,
        version: null,
      }
    }
    try {
      const info = await readFile(path.join(destination, 'Info.lua'), 'utf8')
      const version = info.match(/display\s*=\s*['"]([^'"]+)['"]/)?.[1] || null
      return {
        supported: true,
        installed: true,
        pluginPath: destination,
        version,
      }
    } catch {
      return {
        supported: true,
        installed: false,
        pluginPath: destination,
        version: null,
      }
    }
  }

  async install(params: { port: number; secret: string }) {
    const destination = this.destinationPath()
    if (!destination) throw new Error('รองรับปลั๊กอินบน macOS และ Windows เท่านั้น')
    const sourceInfo = await stat(path.join(this.sourcePath, 'Info.lua'))
    if (!sourceInfo.isFile()) throw new Error('ไม่พบชุดติดตั้งปลั๊กอิน Lightroom')

    await mkdir(path.dirname(destination), { recursive: true })
    await cp(this.sourcePath, destination, { recursive: true, force: true })
    await atomicWrite(
      path.join(destination, 'BridgeConfig.lua'),
      [
        '-- Generated by Ciiya Sync. Do not share this file.',
        'return {',
        `  endpoint = "http://127.0.0.1:${params.port}",`,
        `  secret = "${luaString(params.secret)}",`,
        '}',
        '',
      ].join('\n')
    )
    return this.status()
  }

  async refreshConfig(params: { port: number; secret: string }) {
    const status = await this.status()
    if (!status.installed || !status.pluginPath) return status
    await atomicWrite(
      path.join(status.pluginPath, 'BridgeConfig.lua'),
      [
        '-- Generated by Ciiya Sync. Do not share this file.',
        'return {',
        `  endpoint = "http://127.0.0.1:${params.port}",`,
        `  secret = "${luaString(params.secret)}",`,
        '}',
        '',
      ].join('\n')
    )
    return this.status()
  }
}
